from app.models.base import Base  # noqa: F401
from app.models.tenant import Tenant  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.customer import Customer  # noqa: F401
from app.models.follow_up import FollowUpRecord  # noqa: F401
from app.models.opportunity import Opportunity  # noqa: F401
from app.models.document import KnowledgeDocument  # noqa: F401
from app.models.chunk import DocumentChunk  # noqa: F401
from app.models.task import Task  # noqa: F401
from app.models.reminder_rule import ReminderRule  # noqa: F401
from app.models.notification import Notification  # noqa: F401
from app.models.report import Report  # noqa: F401
from app.models.rag_query_log import RagQueryLog  # noqa: F401
from app.models.ai_feedback import AiFeedback  # noqa: F401
from app.models.chat_session import ChatSession  # noqa: F401
from app.models.chat_message import ChatMessage  # noqa: F401
from app.models.workflow import Workflow  # noqa: F401
from app.models.workflow_run import WorkflowRun  # noqa: F401
from app.models.knowledge_base import KnowledgeBase  # noqa: F401
from app.models.library_folder import LibraryFolder  # noqa: F401
from app.models.library_file import LibraryFile  # noqa: F401
from app.models.user_group import UserGroup  # noqa: F401
from app.models.llm_model import LlmModel  # noqa: F401
from app.models.llm_call_log import LlmCallLog  # noqa: F401
from app.models.error_log import ErrorLog  # noqa: F401
from app.models.industry import Industry  # noqa: F401
from app.models.audit_log import AuditLog  # noqa: F401
from app.models.skill import Skill  # noqa: F401
from app.models.skill_call_log import SkillCallLog  # noqa: F401
from app.models.chunk_question import ChunkQuestion  # noqa: F401
from app.models.mcp_server import McpServer  # noqa: F401
from app.models.notebook import Notebook, NotebookNote  # noqa: F401
from app.models.brand_settings import BrandSettings  # noqa: F401
from app.models.resource_permission import ResourcePermission  # noqa: F401
from app.models.document_version import DocumentVersion  # noqa: F401
from app.models.login_attempt import LoginAttempt  # noqa: F401
from app.models.login_code import LoginCode  # noqa: F401
from app.models.system_setting import SystemSetting  # noqa: F401
from app.models.agent_approval import AgentApproval  # noqa: F401
